dependencies:
  - changed-files:
      - any-glob-to-any-file: .github/dependabot.yml
      - any-glob-to-any-file: go.mod
      - any-glob-to-any-file: go.sum
documentation:
  - changed-files:
      - any-glob-to-any-file: website/**/*