blank_issues_enabled: false
contact_links:
  - name: Terraform Provider Questions
    url: https://discuss.hashicorp.com/c/terraform-providers/31
    about: GitHub issues in this repository are only intended for bug reports and feature requests. Other issues will be closed. Please ask and answer questions through the Terraform Provider section of HashiCorp Discuss.
  - name: Terraform Language or Workflow Questions
    url: https://discuss.hashicorp.com/c/terraform-core
    about: Please ask and answer language or workflow related questions through the Terraform Core section of HashiCorp Discuss.
